
  const data = [
    {
      id: 1,
      company: "Google",
      logo: "https://logo.clearbit.com/google.com",
      role: "Frontend Developer",
      tag: "Junior Level",
      salary: "$35/hr",
      location: "Bangalore, India",
      posted: "2 days ago",
    },
    {
      id: 2,
      company: "Amazon",
      logo: "https://logo.clearbit.com/amazon.com",
      role: "Backend Engineer",
      tag: "Senior Level",
      salary: "$60/hr",
      location: "Hyderabad, India",
      posted: "5 days ago",
    },
    {
      id: 3,
      company: "Microsoft",
      logo: "https://logo.clearbit.com/microsoft.com",
      role: "Full Stack Developer",
      tag: "Mid Level",
      salary: "$50/hr",
      location: "Noida, India",
      posted: "1 day ago",
    },
    {
      id: 4,
      company: "Apple",
      logo: "https://logo.clearbit.com/apple.com",
      role: "iOS Developer",
      tag: "Senior Level",
      salary: "$70/hr",
      location: "Remote",
      posted: "3 days ago",
    },
    {
      id: 5,
      company: "Meta",
      logo: "https://logo.clearbit.com/meta.com",
      role: "React Developer",
      tag: "Junior Level",
      salary: "$40/hr",
      location: "Gurgaon, India",
      posted: "7 days ago",
    },
    {
      id: 6,
      company: "Netflix",
      logo: "https://logo.clearbit.com/netflix.com",
      role: "UI Engineer",
      tag: "Senior Level",
      salary: "$80/hr",
      location: "Remote",
      posted: "4 days ago",
    },
    {
      id: 7,
      company: "Adobe",
      logo: "https://logo.clearbit.com/adobe.com",
      role: "Software Engineer",
      tag: "Mid Level",
      salary: "$55/hr",
      location: "Noida, India",
      posted: "6 days ago",
    },
    {
      id: 8,
      company: "Uber",
      logo: "https://logo.clearbit.com/uber.com",
      role: "Backend Developer",
      tag: "Senior Level",
      salary: "$65/hr",
      location: "Bangalore, India",
      posted: "9 days ago",
    },
    {
      id: 9,
      company: "Airbnb",
      logo: "https://logo.clearbit.com/airbnb.com",
      role: "Frontend Engineer",
      tag: "Junior Level",
      salary: "$45/hr",
      location: "Remote",
      posted: "8 days ago",
    },
    {
      id: 10,
      company: "LinkedIn",
      logo: "https://logo.clearbit.com/linkedin.com",
      role: "Full Stack Engineer",
      tag: "Mid Level",
      salary: "$58/hr",
      location: "Bangalore, India",
      posted: "10 days ago",
    },
  ]; 
  export default data;

  